// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyWeb.Models
{
    public partial class Opera
    {
        public Opera()
        {
            Comments = new HashSet<Comment>();
        }

        [Key]
        [Column("OperaID")]
        public int OperaId { get; set; }
        [Required]
        [StringLength(200)]
        public string Title { get; set; }
        public int? Year { get; set; }
        [Required]
        public string Composer { get; set; }

        [InverseProperty(nameof(Comment.Opera))]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}