// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarterM.Data;

namespace StarterM.Migrations
{
    [DbContext(typeof(OperaContext))]
    partial class OperaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StarterM.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("OperaID")
                        .HasColumnType("int");

                    b.Property<string>("UserComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentId");

                    b.HasIndex("OperaID");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            LastModified = new DateTime(2022, 2, 24, 9, 43, 52, 41, DateTimeKind.Local).AddTicks(767),
                            OperaID = 1,
                            UserComment = "comment1",
                            UserName = "user1"
                        },
                        new
                        {
                            CommentId = 2,
                            LastModified = new DateTime(2022, 2, 24, 9, 43, 52, 42, DateTimeKind.Local).AddTicks(3400),
                            OperaID = 1,
                            UserComment = "comment2",
                            UserName = "user2"
                        },
                        new
                        {
                            CommentId = 3,
                            LastModified = new DateTime(2022, 2, 24, 9, 43, 52, 42, DateTimeKind.Local).AddTicks(3418),
                            OperaID = 2,
                            UserComment = "comment3",
                            UserName = "user3"
                        },
                        new
                        {
                            CommentId = 4,
                            LastModified = new DateTime(2022, 2, 24, 9, 43, 52, 42, DateTimeKind.Local).AddTicks(3421),
                            OperaID = 2,
                            UserComment = "comment4",
                            UserName = "user4"
                        });
                });

            modelBuilder.Entity("StarterM.Models.Opera", b =>
                {
                    b.Property<int>("OperaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Composer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("OperaID");

                    b.ToTable("Operas");

                    b.HasData(
                        new
                        {
                            OperaID = 1,
                            Composer = "Wolfgang Amadeus Mozart",
                            Title = "Cosi Fan Tutte",
                            Year = 1790
                        },
                        new
                        {
                            OperaID = 2,
                            Composer = "Giuseppe Verdi",
                            Title = "Rigoletto",
                            Year = 1851
                        },
                        new
                        {
                            OperaID = 3,
                            Composer = "John Adams",
                            Title = "Nixon in China",
                            Year = 1987
                        },
                        new
                        {
                            OperaID = 4,
                            Composer = "Alban Berg",
                            Title = "Wozzeck",
                            Year = 1922
                        });
                });

            modelBuilder.Entity("StarterM.Models.Comment", b =>
                {
                    b.HasOne("StarterM.Models.Opera", "Opera")
                        .WithMany("Comments")
                        .HasForeignKey("OperaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opera");
                });

            modelBuilder.Entity("StarterM.Models.Opera", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
